# Generated by Django 3.2 on 2021-06-04 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Pojazd', 'verbose_name_plural': 'Pojazdy'},
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa czynności')),
                ('data_wykonania', models.DateTimeField(default=django.utils.timezone.now)),
                ('przebieg', models.PositiveIntegerField(default='1', verbose_name='Przebieg')),
                ('koszt', models.PositiveIntegerField(default='1', verbose_name='Koszt')),
                ('uwagi', models.TextField(verbose_name='Uwagi')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Czynność',
                'verbose_name_plural': 'Czynności',
            },
        ),
    ]
