# Generated by Django 3.2 on 2021-06-04 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_auto_20210604_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data_wykonania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
